config/routes.rb
Rails.application.routes.draw do
  resources :orders

  resources :addresses

  resources :customers

end

app/models/address.rb
class Address < ActiveRecord::Base
  validates(:street, presence: true)
  validates(:number, numericality: {greater_than_or_equal_to: 1})
  validates(:town, presence: true)

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  validates(:name, presence: true)

  has_one :address

  accepts_nested_attributes_for :address
end

app/models/order.rb
class Order < ActiveRecord::Base
  validates(:product, presence: true)

  belongs_to :customer

  accepts_nested_attributes_for :customer, :reject_if => :no_name


  def no_name(attributes)
    attributes[:name].blank?
  end
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :set_address, only: [:show, :edit, :update, :destroy]

  # GET /addresses
  # GET /addresses.json
  def index
    @addresses = Address.all
  end

  # GET /addresses/1
  # GET /addresses/1.json
  def show
  end

  # GET /addresses/new
  def new
    @address = Address.new
  end

  # GET /addresses/1/edit
  def edit
  end

  # POST /addresses
  # POST /addresses.json
  def create
    @address = Address.new(address_params)

    respond_to do |format|
      if @address.save
        format.html { redirect_to @address, notice: 'Address was successfully created.' }
        format.json { render :show, status: :created, location: @address }
      else
        format.html { render :new }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /addresses/1
  # PATCH/PUT /addresses/1.json
  def update
    respond_to do |format|
      if @address.update(address_params)
        format.html { redirect_to @address, notice: 'Address was successfully updated.' }
        format.json { render :show, status: :ok, location: @address }
      else
        format.html { render :edit }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1
  # DELETE /addresses/1.json
  def destroy
    @address.destroy
    respond_to do |format|
      format.html { redirect_to addresses_url, notice: 'Address was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_address
      @address = Address.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def address_params
      params.require(:address).permit(:street, :number, :town)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:name)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
    @order.build_customer if @order.customer.nil?
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @order.build_customer if @order.customer.nil?
    respond_to do |format|
      if @order.save and @order.customer.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:product, customer_attributes: [:name])
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/addresses/_form.html.haml
= form_for(@address) do |f|
  - if @address.errors.any?
    #error_explanation
      %h2
        = pluralize(@address.errors.count, "error")
        prohibited this address from being saved:
      %ul
        - @address.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :street
    %br/
    = f.text_field :street
  .field
    = f.label :number
    %br/
    = f.number_field :number
  .field
    = f.label :town
    %br/
    = f.text_field :town
  .actions
    = f.submit

app/views/addresses/edit.html.haml
%h1 Editing address
= render 'form'
= link_to 'Show', @address
|
\#{link_to 'Back', addresses_path}

app/views/addresses/index.html.haml
%h1 Listing addresses
%table
  %thead
    %tr
      %th Street
      %th Number
      %th Town
      %th{:colspan => "3"}
  %tbody
    - @addresses.each do |address|
      %tr
        %td= address.street
        %td= address.number
        %td= address.town
        %td= link_to 'Show', address
        %td= link_to 'Edit', edit_address_path(address)
        %td= link_to 'Destroy', address, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Address', new_address_path

app/views/addresses/new.html.haml
%h1 New address
= render 'form'
= link_to 'Back', addresses_path

app/views/addresses/show.html.haml
%p#notice= notice
%p
  %strong Street:
  = @address.street
%p
  %strong Number:
  = @address.number
%p
  %strong Town:
  = @address.town
= link_to 'Edit', edit_address_path(@address)
|
\#{link_to 'Back', addresses_path}

app/views/customers/_form.html.haml
= form_for(@customer) do |f|
  - if @customer.errors.any?
    #error_explanation
      %h2
        = pluralize(@customer.errors.count, "error")
        prohibited this customer from being saved:
      %ul
        - @customer.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .actions
    = f.submit

app/views/customers/edit.html.haml
%h1 Editing customer
= render 'form'
= link_to 'Show', @customer
|
\#{link_to 'Back', customers_path}

app/views/customers/index.html.haml
%h1 Listing customers
%table
  %thead
    %tr
      %th Name
      %th{:colspan => "3"}
  %tbody
    - @customers.each do |customer|
      %tr
        %td= customer.name
        %td= link_to 'Show', customer
        %td= link_to 'Edit', edit_customer_path(customer)
        %td= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Customer', new_customer_path

app/views/customers/new.html.haml
%h1 New customer
= render 'form'
= link_to 'Back', customers_path

app/views/customers/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @customer.name
= link_to 'Edit', edit_customer_path(@customer)
|
\#{link_to 'Back', customers_path}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Pizzeria
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = yield

app/views/orders/_form.html.haml
= form_for(@order) do |f|
  - if @order.errors.any?
    #error_explanation
      %h2
        = pluralize(@order.errors.count, "error")
        prohibited this order from being saved:
      %ul
        - @order.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :product
    %br/
    = f.text_field :product
  = f.fields_for :customer do |customer_attributes|
    .field
      = customer_attributes.label :name
      %br/
      = customer_attributes.text_field :name
  .actions
    = f.submit

app/views/orders/edit.html.haml
%h1 Editing order
= render 'form'
= link_to 'Show', @order
|
\#{link_to 'Back', orders_path}

app/views/orders/index.html.haml
%h1 Listing orders
%table
  %thead
    %tr
      %th Product
      %th Customer
      %th Address
      %th{:colspan => "3"}
  %tbody
    - @orders.each do |order|
      %tr
        %td= order.product
        %td= order.customer.name
        %td= link_to 'Show', order
        %td= link_to 'Edit', edit_order_path(order)
        %td= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Order', new_order_path

app/views/orders/new.html.haml
%h1 New order
= render 'form'
= link_to 'Back', orders_path

app/views/orders/show.html.haml
%p#notice= notice
%p
  %strong Product:
  = @order.product
  %br/
  %strong Customer:
  = @order.customer.name
  %br/
= link_to 'Edit', edit_order_path(@order)
|
\#{link_to 'Back', orders_path}